### ISSUE TITLE
Font Override does not work with Nord Color Scheme

### ISSUE THREAD

**Issue by fionera** [arcticicestudio/nord-jetbrains-editor#38]
I installed it via the Plugin but now I cannot use the Font override

**Comment by arcticicestudio** [comment]
Thanks for our contribution 👍 

I've also noticed this after setting up IntelliJ on a freshly installed system. Even if I think that this is a problem of IntelliJ itself I'll remove the font definition from the theme. In my view IntelliJ should prioritize the font override of the user higher than the one defined in a theme instead of the other way around.

Anyway, user who haven't installed “Source Code Pro“ on their system might also have problems when the font is defined in the theme so removing it might fix such problems too 😄

**Comment by fionera** [comment]
I found out I can override it under "Editor -> Color Scheme -> Color Scheme Font"

**Comment by GauthierPLM** [comment]
In #40 I removed the font set by the color scheme so the user's choice is respected by the IDE.
Color scheme's font is a relic of the old theming system of IntelliJ, which is now replaced by font settings outside of color scheme settings;
